services:
  superbros-coder-sveltekit:
    container_name: superbros-coder-sveltekit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
